/*
 * SevenSegment_Config.h
 *
 * Created: 3/7/2024 11:40:16 AM
 *  Author: Ahmed Mohammed
 */ 


#ifndef SEVENSEGMENT_CONFIG_H_
#define SEVENSEGMENT_CONFIG_H_

#include "common.h"

#include "SevenSegment_Interface.h"

/** At @ref SEVEN_SEGMENT_COMMON_MODE_define **/
#define SEVEN_SEGMENT_COMMON_MODE					SEVEN_SEGMENT_COMMON_CATHODE

/** At @ref SEVEN_SEGMENT_BCD_MODE_define **/
#define SEVEN_SEGMENT_BCD_MODE						SEVEN_SEGMENT_WITHOUT_BCD

/** At @ref SEVEN_SEGMENT_DATA_PORT_define **/
#define SEVEN_SEGMENT_DATA_PORT						SEVEN_SEGMENT_DATA_PORTB


/* for bcd mode use the first pins only */
/** At @ref SEVEN_SEGMENT_PIN_define **/
#define SEVEN_SEGMENT_PINA							SEVEN_SEGMENT_PIN0
#define SEVEN_SEGMENT_PINB							SEVEN_SEGMENT_PIN1
#define SEVEN_SEGMENT_PINC							SEVEN_SEGMENT_PIN2
#define SEVEN_SEGMENT_PIND							SEVEN_SEGMENT_PIN3

#define SEVEN_SEGMENT_PINE							SEVEN_SEGMENT_PIN4
#define SEVEN_SEGMENT_PINF							SEVEN_SEGMENT_PIN5
#define SEVEN_SEGMENT_PING							SEVEN_SEGMENT_PIN6
//#define SEVEN_SEGMENT_PIN_DOT						SEVEN_SEGMENT_PIN3

/* This driver supports four seven segments only */
/** At @ref SEVEN_SEGMENT_PIN_define && At @ref SEVEN_SEGMENT_ENABLE_PORT_define **/
#define SEVEN_SEGMENT_ENABLE_SEG1_PORT				SEVEN_SEGMENT_DATA_PORTA
#define SEVEN_SEGMENT_ENABLE_SEG1_PIN				SEVEN_SEGMENT_PIN0

#define SEVEN_SEGMENT_ENABLE_SEG2_PORT				SEVEN_SEGMENT_DATA_PORTA
#define SEVEN_SEGMENT_ENABLE_SEG2_PIN				SEVEN_SEGMENT_PIN1

#define SEVEN_SEGMENT_ENABLE_SEG3_PORT				SEVEN_SEGMENT_DATA_PORTA
#define SEVEN_SEGMENT_ENABLE_SEG3_PIN				SEVEN_SEGMENT_PIN2

#define SEVEN_SEGMENT_ENABLE_SEG4_PORT				SEVEN_SEGMENT_DATA_PORTA
#define SEVEN_SEGMENT_ENABLE_SEG4_PIN				SEVEN_SEGMENT_PIN3



#endif /* SEVENSEGMENT_CONFIG_H_ */